spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.100:3306/note
    username: note
    password: note
  jpa:
    open-in-view: false
    show-sql: true
